import io
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

def generate_notes_pdf(
    lecture_title: str, 
    date_str: str, 
    summary: str, 
    bullet_notes: list, 
    flashcards: list, 
    quizzes: list,
    transcript: list = None
) -> io.BytesIO:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=54,
        leftMargin=54,
        topMargin=54,
        bottomMargin=54
    )
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=24,
        leading=28,
        textColor=colors.HexColor('#1E293B'),
        spaceAfter=5
    )
    
    date_style = ParagraphStyle(
        'DocDate',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=9,
        leading=12,
        textColor=colors.HexColor('#64748B'),
        spaceAfter=15
    )
    
    h1_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=15,
        leading=19,
        textColor=colors.HexColor('#2563EB'),
        spaceBefore=15,
        spaceAfter=10,
        keepWithNext=True
    )
    
    body_style = ParagraphStyle(
        'Body',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#334155'),
        spaceAfter=8
    )
    
    transcript_time_style = ParagraphStyle(
        'TransTime',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8,
        leading=12,
        textColor=colors.HexColor('#2563EB')
    )

    bullet_style = ParagraphStyle(
        'BulletItem',
        parent=body_style,
        leftIndent=15,
        firstLineIndent=-10,
        spaceAfter=6
    )
    
    bold_body_style = ParagraphStyle(
        'BoldBody',
        parent=body_style,
        fontName='Helvetica-Bold'
    )

    story = []
    
    # Title & Date
    story.append(Paragraph(f"Lecture Notes: {lecture_title}", title_style))
    story.append(Paragraph(f"Study Session Date: {date_str} | Generated by Lecture Voice-to-Notes AI", date_style))
    story.append(Spacer(1, 10))
    
    # Summary
    if summary:
        story.append(Paragraph("Executive Summary", h1_style))
        story.append(Paragraph(summary, body_style))
        story.append(Spacer(1, 10))
        
    # Bullet Notes
    if bullet_notes:
        story.append(Paragraph("Key Takeaways & Concepts", h1_style))
        for note in bullet_notes:
            story.append(Paragraph(f"&bull; {note}", bullet_style))
        story.append(Spacer(1, 10))

    # Transcript viewer
    if transcript:
        story.append(PageBreak())
        story.append(Paragraph("Interactive Transcript", h1_style))
        
        transcript_rows = []
        for seg in transcript:
            start_seconds = seg.get("start", 0)
            mins = int(start_seconds // 60)
            secs = int(start_seconds % 60)
            timestamp_str = f"[{mins:02d}:{secs:02d}]"
            
            time_p = Paragraph(timestamp_str, transcript_time_style)
            text_p = Paragraph(seg.get("text", ""), body_style)
            transcript_rows.append([time_p, text_p])
            
        t_table = Table(transcript_rows, colWidths=[60, 440])
        t_table.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 4),
            ('TOPPADDING', (0,0), (-1,-1), 4),
            ('LEFTPADDING', (0,0), (-1,-1), 0),
            ('RIGHTPADDING', (0,0), (-1,-1), 0),
        ]))
        story.append(t_table)
        story.append(Spacer(1, 10))
        
    # Flashcards
    if flashcards:
        story.append(PageBreak())
        story.append(Paragraph("Flashcards & Key Terms", h1_style))
        
        flashcard_data = []
        for i, fc in enumerate(flashcards, 1):
            q_para = Paragraph(f"<b>Q{i}:</b> {fc.get('question', '')}", body_style)
            a_para = Paragraph(f"<b>A:</b> {fc.get('answer', '')}", body_style)
            flashcard_data.append([q_para, a_para])
            
        t = Table(flashcard_data, colWidths=[250, 250])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F8FAFC')),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 10),
            ('TOPPADDING', (0,0), (-1,-1), 10),
            ('LEFTPADDING', (0,0), (-1,-1), 10),
            ('RIGHTPADDING', (0,0), (-1,-1), 10),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#E2E8F0')),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#E2E8F0')),
        ]))
        story.append(t)
        story.append(Spacer(1, 10))
        
    # Quizzes
    if quizzes:
        story.append(PageBreak())
        story.append(Paragraph("Lecture Quiz & Answer Key", h1_style))
        
        for i, q in enumerate(quizzes, 1):
            story.append(Paragraph(f"<b>Question {i}:</b> {q.get('question', '')}", bold_body_style))
            
            # Show Options (if present)
            options = q.get('options', [])
            if options:
                for j, opt in enumerate(options):
                    opt_letter = chr(65 + j) # A, B, C, D
                    story.append(Paragraph(f"[{opt_letter}] {opt}", bullet_style))
                
            story.append(Paragraph(f"<i>Correct Answer:</i> <b>{q.get('correct_answer', '')}</b>", body_style))
            if q.get('explanation'):
                story.append(Paragraph(f"<i>Explanation:</i> {q.get('explanation')}", body_style))
            story.append(Spacer(1, 10))
            
    doc.build(story)
    buffer.seek(0)
    return buffer
